name: Build & Deploy to ftp
run-name: ${{ github.actor }} is sending the website to the ftp server
on: [push]
jobs:
  build-deploy-website:
    runs-on: ubuntu-latest
    steps:
      # give stats for the logs
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      #check out repo
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      #configure node
      - run: echo "The workflow is now ready build the website."
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
      # Install dependencies build and cache them
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      # Deploy to the ftp server using a public workflow
      - name: List files in the repository after building
        run: |
          ls ${{ github.workspace }}
      - name: Deploy to ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          # server-dir: commented out because default is root dir
          #not in the export path but just in case
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt

      # Declare if we are successful
      - run: echo "This job's status is ${{ job.status }}."
